#!/bin/bash
# Script para listar e documentar os comandos do Discord

echo "============================================"
echo "  YUI BOT - COMANDOS DISCORD"
echo "============================================"
echo ""
echo "Comandos Slash disponíveis:"
echo ""
echo "  /yui-diario"
echo "    Descrição: Consulta sob demanda o resumo diário atual do GTA Online"
echo "    (Gun Van, Dealers, Collectibles, Time Trials)"
echo ""
echo "  /yui-semanal"
echo "    Descrição: Consulta sob demanda os eventos e descontos da semana atual"
echo "    (Bônus, Descontos, Veículo do Pódio)"
echo ""
echo "  /yui-noticias [quantidade]"
echo "    Descrição: Exibe as últimas notícias publicadas no Rockstar Newswire"
echo "    Parâmetro opcional: quantidade (1-5, padrão: 2)"
echo ""
echo "============================================"
echo "  Para implantar os comandos no Discord:"
echo "  npm run deploy:commands"
echo "============================================"
